//
// Created by alex on 25.04.2021.
//
/**
 * VESC - a smart electric speed controller (ESC) for a vehicle (V)
 * Used with a BLDC mode at that moment.
 * Can be used with a FOC and PMSM mode as well
 *
 * Basic control require PPM (Pulse Position Modulation) signal
 * That signal is generated by Timer2 on Channel 1
 *
 * Later communication with VESC via UART will be added
 * (Via UART you can configure any parameter of the controller, max current, for example)
 * Now there is only PPM signal which set the current of the motor.
 *
 */
#include "vesc.h"
#include "stm32f1xx_ll_tim.h"

/**
 * Initialization of the timer - set middle value of the PPM signal and enabling channel and timer
 */
void VESC_Init(void){
    VESC_SetPPM(128);
    LL_TIM_CC_EnableChannel(TIM2, LL_TIM_CHANNEL_CH1);
    LL_TIM_EnableCounter(TIM2);
}

/**
 * Set a PPM
 *
 * PPM works in the range from 1 to 2 ms there 1 is min value and 2 is max (it's pretty obvious, isn't it? :D)
 * PPM signal is generated as PWM signal with reload value 5100 and prescaler 251.
 * Frequency of the PPM is 50 Hz
 * Changing duty cycle in range from 255 to 510 you can change pulse width from 1 to 2 ms
 * To set pulse width from 1ms duty cycle (not from 0ms), obviously, offset must be used
 *
 * @param ppm - 8-bit value of the duty cycle in the "PPM notation" (from 1 to 2 ms)
 */
void VESC_SetPPM(uint8_t ppm){
    uint16_t value = ppm + 255;
    LL_TIM_OC_SetCompareCH1(TIM2, value);
}